version: "1"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
